### ISSUE TITLE
Error converting biogrid

### ISSUE THREAD

**Issue by 10mubeen** [bio2bel/bio2bel#38]
Hey Charlie,

I got the following error with BioGrid:

```python-traceback
/usr/local/bin/python3.7 /Users/sarahbeenie/PathwayProjects/bio2bel/src/bio2bel/sources/biogrid.py
Converting
[ncbitaxon] parsing obo: 18.0Mit [36:34, 8.22kit/s]
Traceback (most recent call last):
  File "/Users/sarahbeenie/PathwayProjects/bio2bel/src/bio2bel/sources/biogrid.py", line 376, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/sarahbeenie/PathwayProjects/bio2bel/src/bio2bel/sources/biogrid.py", line 368, in main
    graph = get_bel()
  File "/Users/sarahbeenie/PathwayProjects/bio2bel/src/bio2bel/sources/biogrid.py", line 242, in get_bel
    df = get_processed_biogrid()
  File "/Users/sarahbeenie/PathwayProjects/bio2bel/src/bio2bel/sources/biogrid.py", line 230, in get_processed_biogrid
    df['#ID Interactor A'] = df['#ID Interactor A'].map(_process_interactor)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 3630, in map
    new_values = super()._map_values(arg, na_action=na_action)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/base.py", line 1145, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "/Users/sarahbeenie/PathwayProjects/bio2bel/src/bio2bel/sources/biogrid.py", line 152, in _process_interactor
    ncbigene_identifier = _map_ncbigene(identifier)
  File "/Users/sarahbeenie/PathwayProjects/bio2bel/src/bio2bel/sources/biogrid.py", line 118, in _map_ncbigene
    return _get_ncbigene_mapping().get(identifier)
  File "/Users/sarahbeenie/PathwayProjects/bio2bel/src/bio2bel/sources/biogrid.py", line 114, in _get_ncbigene_mapping
    return pyobo.sources.biogrid.get_ncbigene_mapping()
  File "/usr/local/lib/python3.7/site-packages/pyobo/cache_utils.py", line 48, in _wrapped
    rv = f()
  File "/usr/local/lib/python3.7/site-packages/pyobo/sources/biogrid.py", line 75, in get_ncbigene_mapping
    df = df[df['IDENTIFIER_TYPE'] == 'ENTREZ_GENE', ['BIOGRID_ID', 'IDENTIFIER_VALUE']]
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 116, in pandas._libs.index.IndexEngine.get_loc
TypeError: '(0           False
1           False
2           False
3           False
4            True
            ...  
45655390    False
45655391    False
45655392    False
45655393    False
45655394    False
Name: IDENTIFIER_TYPE, Length: 45655395, dtype: bool, ['BIOGRID_ID', 'IDENTIFIER_VALUE'])' is an invalid key

Process finished with exit code 1
```

 Any idea what's going on?

Thank you!

**Comment by cthoyt** [comment]
what does the output of the following say on your machine?

```python
import bio2bel
print(bio2bel.get_version(with_git_hash=True))
```

**Comment by 10mubeen** [comment]
0.3.9-dev-c69bda4c
0.2.4-UNHASHED

**Comment by cthoyt** [comment]
I wonder if it's a pandas problem. I'm on `pandas==1.0.3`, I wonder if you're on a crazy old version because you installed some of daniel's code where he pinned it to old versions. Check that out, if you're on an old one, do `pip install --upgrade pandas` and see if that fixes it. Otherwise I'll investigate further

**Comment by cthoyt** [comment]
Okay so it seems that I've been working with unsafe usage of the slice operator in pandas. The correct code uses `.loc[]` like the following:

```python
df.loc[df['IDENTIFIER_TYPE'] == 'ENTREZ_GENE', ['BIOGRID_ID', 'IDENTIFIER_VALUE']]
```

**Comment by cthoyt** [comment]
@10mubeen please see upstream fix in https://github.com/pyobo/pyobo/commit/d9d356217cb0254ea877ef34b14c215f29de7624

I still have to do a bit of checking to see if the version bump of biogrid leads to new species that are unhandled, though!
